<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
* This class handles all functions that will send 
* autogenerated emails
*
* @link https://code.google.com/p/onlineprojectplanner/
*/
class Emailsender
{ 
	private $_CI = null;
  private $_last_error = "";
    
	function __construct()
	{
		// get CI instance
		$this->_CI = & get_instance();
		
		// Load the email library
		$this->_CI->load->library('email');
	}
	
	/**
	* This function will return the last error
	* this class has set.
	*/
	function GetLastError()
	{
			// save error, clear message and return
			$returnStr = $this->_last_error;    
			$this->_last_error = "";
			return $returnStr;
	}
	
	/**
	* Function: SendActivationMail
	* This function will send a activation-email
	* 
	* @param string $name
	* @param string $email
	* @param string $code
	* @return bool
	*/
	function SendActivationMail($name, $email, $code)
	{
		$this->_CI->email->from('info@example.com', 'Superwiki');
		$this->_CI->email->to($email); 

		$this->_CI->email->subject('Activation email');
		$this->_CI->email->message("Dear " . $name . "<br />This email is autogenerated because you have tried to register at " . site_url() . ".<br /><br />Click on the link below to activate:<br /><a href='" . site_url('user_controller/Activate') . "/" . $code . "'>" . site_url('user_controller/Activate') . "/" . $code . "</a> ");

		return $this->_CI->email->send();
	}
	
	/**
	* Function: SendRecommendationMail
	* This function will send a recommendation mail
	* 
	* @param string $senderName
	* @param string $email
	* @return bool
	*/
	function SendRecommendationMail($senderName, $email)
	{
		$this->_CI->email->from('info@example.com', 'Superwiki');
		$this->_CI->email->to($email); 

		$this->_CI->email->subject('Recommendation email from '. $senderName);
		$this->_CI->email->message("Hello<br />Your friend " . $senderName . " would like you to join this awesome applikation \"Superwiki\".<br /> You can find more information here, <a href='" . site_url() . "'>" . site_url() . "</a>");

		return $this->_CI->email->send();
	}
    
    
    
    /**
    * This will send the reset password email
    * with the initial confirmation code.
    * 
    * @param string $name
    * @param string $email
    * @param int $code
    * $param int $uid
    * @return bool
    */
    function SendResetPasswordMail($name, $email, $code, $uid)
    {
        
        // prepare email to send
        $system_email = $this->_CI->config->item('system_email', 'webclient');
        $system_email_name = $this->_CI->config->item('system_email_name', 'webclient');
        $email_template = $this->_CI->config->item('reset_password_template', 'webclient');
        $confirm_url = $this->_CI->config->item('confirm_reset_url', 'webclient');
        $subject = $this->_CI->config->item('reset_password_template_subject', 'webclient');
        
        $confirm_url = sprintf(site_url().$confirm_url, $uid, $code);
        $email_template = sprintf($email_template, $name, $confirm_url, $system_email_name);

        // user CI library email
        $this->_CI->load->library('email');
        
        $this->_CI->email->from($system_email, $system_email_name);
        $this->_CI->email->to($email); 
        $this->_CI->email->subject($subject);
        $this->_CI->email->message($email_template); 
        
        // send
        if ( $this->_CI->email->send() == false )
        {
            // failed to send..
            return false;
        }     
        
        
        // all ok
        return true;
    }
    
    
    /**
    * This function will send an email with the newly
    * generated password.
    * 
    * @param string $name
    * @param string $email
    * @param string $new_password
    * @return bool
    */
    function SendNewPasswordEmail($name, $email, $new_password)
    {
        
        // email new password to user
        $system_email = $this->_CI->config->item('system_email', 'webclient');
        $system_email_name = $this->_CI->config->item('system_email_name', 'webclient');
        $email_template = $this->_CI->config->item('new_password_template', 'webclient');
        $subject = $this->_CI->config->item('new_password_template_subject', 'webclient');
        
        $email_template = sprintf($email_template, $name, $new_password, $system_email_name);

        // user CI library email
        $this->_CI->load->library('email');
        
        $this->_CI->email->from($system_email, $system_email_name);
        $this->_CI->email->to($email); 
        $this->_CI->email->subject($subject);
        $this->_CI->email->message($email_template); 
        
        // send
        if ( $this->_CI->email->send() == false )
        {
            // failed to send..
            return false;
        }  
        
        // all ok
        return true;
    }
    
}

?>