<!-- END: load jqplot -->
<script type="text/javascript" src="<?php echo $widget_base_url; ?>js/init.js"></script>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Stories</a></li>
		<li><a href="#tabs-2">Burndown chart</a></li>
	</ul>
	
	<div id="tabs-1">

		<div id="story-dialog-form" title="Add new story">
			<p class="validateTips">All form fields are required.</p>
	
			<form method="post" action="" onsubmit="return false" class="story_form">
				<fieldset>
					<label for="story">Story</label>
					<input type="text" name="story" id="story" class="text ui-widget-content ui-corner-all" />
					<label for="assignee">Assignee</label>
					<input type="text" name="assignee" id="assignee" value="" class="text ui-widget-content ui-corner-all" />
					<label for="description">Description</label>
					<input type="text" name="description" id="description" value="" class="text ui-widget-content ui-corner-all" />
					<label for="points">Total points</label>
					<input type="text" name="points" id="points" value="" class="text ui-widget-content ui-corner-all" />
				</fieldset>
			</form>
		</div>
		
		
		<div id="edit-story-dialog-form" title="Edit story">
			<p class="validateTips">All form fields are required.</p>
	
			<form method="post" action="" onsubmit="return false" class="story_form">
				<fieldset>
					<input id="edit_story_id" type="hidden" name="story_id" value="" />
					<label for="story">Story</label>
					<input type="text" name="story" id="edit_story_name" class="text ui-widget-content ui-corner-all" />
					<label for="assignee">Assignee</label>
					<input type="text" name="assignee" id="edit_assignee" value="" class="text ui-widget-content ui-corner-all" />
					<label for="description">Description</label>
					<input type="text" name="description" id="edit_description" value="" class="text ui-widget-content ui-corner-all" />
					<label for="points">Total points</label>
					<input type="text" name="points" id="edit_points" value="" class="text ui-widget-content ui-corner-all" />
				</fieldset>
			</form>
		</div>
		
		<div id="delete-story-dialog-form" title="Delete story">
			<p id="delete_story_name"></p>
			<input id="delete_story_id" type="hidden" name="delete_id" value="" />
		</div>
		
		<div id="points-story-dialog-form" title="Edit/View points">
			<p id="points_info"></p>
			<form method="post" id="sprint_planner_points_form" action="" onsubmit="return false" class="story_form">
				<!-- Generated by JavaScript -->
			</form>
		</div>
		
		<table id="stories_table" border="0" class="ui-widget">
		
			<thead class="ui-widget-header">
				<tr>
					<th>Story</th>
					<th>Assignee</th>
					<th>Description</th>
					<th>Points</th>
					<th id="sprint_planner_create_button_container"><button id="create-story" class="add">Add</button></th>
				</tr>
			</thead>
			
			<tbody id="story_table_content" class="ui-widget-content">
				<!-- Content generated by JS -->
			</tbody>
		</table>

	</div>

	<div id="tabs-2">
	    <div id="chart1" data-height="260px" data-width="600px" style="margin-top:20px; margin-left:20px;"></div>
	</div>


</div>