<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
* This class handles all functions that will send 
* autogenerated emails
*
* @link https://code.google.com/p/onlineprojectplanner/
*/
class Emailsender
{ 
	private $_CI = null;
  private $_last_error = "";
    
	function __construct()
	{
		// get CI instance
		$this->_CI = & get_instance();
		
		// Load the email library
		$this->_CI->load->library('email');
	}
	
	/**
	* This function will return the last error
	* this class has set.
	*/
	function GetLastError()
	{
			// save error, clear message and return
			$returnStr = $this->_last_error;    
			$this->_last_error = "";
			return $returnStr;
	}
	
	/**
	* Function: SendActivationMail
	* This function will send a activation-email
	* 
	* @param string $name
	* @param string $email
	* @param string $code
	* @return bool
	*/
	function SendActivationMail($name, $email, $code)
	{
		$this->_CI->email->from('info@example.com', 'Superwiki');
		$this->_CI->email->to($email); 

		$this->_CI->email->subject('Activation email');
		$this->_CI->email->message("Dear " . $name . "<br />This email is autogenerated because you have tried to register at " . site_url() . ".<br /><br />Click on the link below to activate:<br /><a href='" . site_url('user_controller/Activate') . "/" . $code . "'>" . site_url('user_controller/Activate') . "/" . $code . "</a> ");

		return $this->_CI->email->send();
	}
	
	/**
	* Function: SendRecommendationMail
	* This function will send a recommendation mail
	* 
	* @param string $senderName
	* @param string $email
	* @return bool
	*/
	function SendRecommendationMail($senderName, $email)
	{
		$this->_CI->email->from('info@example.com', 'Superwiki');
		$this->_CI->email->to($email); 

		$this->_CI->email->subject('Recommendation email from '. $senderName);
		$this->_CI->email->message("Hello<br />Your friend " . $senderName . " would like you to join this awesome applikation \"Superwiki\".<br /> You can find more information here, <a href='" . site_url() . "'>" . site_url() . "</a>");

		return $this->_CI->email->send();
	}
}

?>