<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');   


/* ---------------------------------------
* Timezone
* --------------------------------------- */

$timezone = "Europe/Stockholm";
@date_default_timezone_set($timezone);


/* ---------------------------------------
* Site title
* --------------------------------------- */

$config['webclient']['site_title'] = "Online Project Planner";


/* ---------------------------------------
* Password salt
* --------------------------------------- */

$config['webclient']['password_salt'] = "21j757d73I";


/* ---------------------------------------
* Theme name (folder in css/.. and views/..)
* - NO ending slash, just the folder name
* --------------------------------------- */

$config['webclient']['theme'] = "default";


/* ---------------------------------------
* Save widget positions (will increase amount
* of traffic to server and database)
* --------------------------------------- */
$config['webclient']['widget_save_positions'] = true;


/* ---------------------------------------
* Default values for a widget (set as global
* javascript variables in library Theme)
* --------------------------------------- */
$config['webclient']['widget_default_height'] = 450;
$config['webclient']['widget_default_width'] = 600;
$config['webclient']['widget_default_x'] = 30;
$config['webclient']['widget_default_y'] = 15;


/* ---------------------------------------
* Widget icon settings
* --------------------------------------- */
$config['webclient']['widget_icon_height'] = 48;
$config['webclient']['widget_icon_width'] = 48;
$config['webclient']['widget_generic_icon_image'] = 'images/buttons/generic_plugin_icon.png';


/* ---------------------------------------
* Delay Widgets-syncronization
* 
* - if true, then sync to database will be
*   delayed by 15 minutes (default) and
*   lower the number of database requests
* --------------------------------------- */

$config['webclient']['delay_widgets_sync'] = false;
$config['webclient']['delay_widgets_sync_minutes'] = 15;


/* ---------------------------------------
* System email (reset password etc)
* - will be used as a "from-address"
* --------------------------------------- */

$config['webclient']['system_email'] = "noreply@".($_SERVER['SERVER_NAME']=='localhost' ? 'mydomain.com' : $_SERVER['SERVER_NAME']); // only localhost will be marked a spam
$config['webclient']['system_email_name'] = "Online Project Planner";


/* ---------------------------------------
* Settings for reset password
* --------------------------------------- */

// url to confirm (first %s is UserID and second %s is confirmation code)
$config['webclient']['confirm_reset_url'] = "account/resetpassword"; // parameters added in library Emailsender

// email template for reset password
$config['webclient']['reset_password_template_subject'] = "Reset password";
$config['webclient']['reset_password_template'] = '<h2>Hi %1$s,</h2><p>Please follow this link or copy/paste it to the adressbar, to confirm password reset and to generate a new password</p><p><b><a href=\"%2$s\">%2$s</a></b></p>';

// email template for new password
$config['webclient']['new_password_template_subject'] = "New password";
$config['webclient']['new_password_template'] = "<h2>Hi %s,</h2><p>Here is your new password:</p><p><b>%s</b></p>";

/* ---------------------------------------
* Settings for activation mail
* --------------------------------------- */
$config['webclient']['activation_template_subject'] = "Activation email";
$config['webclient']['activation_url'] = "account/activate"; // parameters added in library Emailsender
$config['webclient']['activation_template'] = '<h2>Dear %1$s</h2><p>This email is autogenerated because you have tried to register at %2$s.</p><p>Click on the link below or copy/paste it to the adressbar, to activate! </p><p><b><a href=\"%3$s\">%3$s</a> </b></p> ';// <a href="%3$s">%3$s</a>     doesnt send the email


/* ---------------------------------------
* Settings for recommendation mail
* --------------------------------------- */
$config['webclient']['recommendation_template_subject'] = "Recommendation email from %s";
$config['webclient']['recommendation_template'] = '<h2>Hello,</h2><p>Your friend %1$s would like you to join this awesome applikation \"Online Project Planner\".</p><p>You can find more information here, <a href=\"%2$s\">%2$s</a></p>';

/* ---------------------------------------
* Settings for invitation mail
* --------------------------------------- */
$config['webclient']['invitation_template_subject'] = "Invitation email";
$config['webclient']['invitation_template'] = '<h2>Hello</h2> <p>This email is autogenerated because a friend of yours have invited you to become a member of his or her project over at the awesome application \"Online Project Planner\"! %1$s</p>'.
											'<p>To accept the invitation, log in with your \"Online Project Planner\"-account and report your invitation code under project->accept invitation.</p><p><b>Invitation code: %2$s</b></p><p>If you still dont have an account, you can register here: <a href=\"%3$s\">%3$s</a></p>';

